-- Silk Road: table for the Qlodserai "Kristofer" feedback-contact greeting (v4.2.37+)
-- Run once in the Supabase SQL editor (project pryjfosvewnlencqbfxl).
create table if not exists public.feedback (
  id          bigint generated by default as identity primary key,
  name        text,           -- the player's chosen handle (sr_meta.name), e.g. "RugNine"
  contact     text,           -- whatever they typed: email / WhatsApp / etc.
  version     text,
  created_at  timestamptz default now()
);
alter table public.feedback enable row level security;
-- Players (anon key) may INSERT only. No anon SELECT, so no one can read others' contacts.
create policy "anon insert feedback" on public.feedback
  for insert to anon with check (true);
-- Read your submissions from the dashboard / with the service role.
